confraria/produto/urls.py
from django.urls import path, include
from .views import (
  ProdutoListView, ProdutoCreateView, ProdutoUpdateView,
  MovimentacaoListView, MovimentacaoCreateView, MovimentacaoDetailView,
  CategoriaCreateView, CategoriaListView, GerarPdfMovimentacaoView
  )

urlpatterns = [
    path('list/', ProdutoListView.as_view(), name='produto_list'),
    path('create/', ProdutoCreateView.as_view(), name='produto_form'),
    path('update/<int:pk>/', ProdutoUpdateView.as_view(), name='produto_form'),
    path('categoria/', CategoriaCreateView.as_view(), name='categoria_form'),
    path('categoria/list/', CategoriaListView.as_view(), name='categoria_list'),
    path('movimentacao/', include([
        path('list/', MovimentacaoListView.as_view(), name='movimentacao_list'),
        path('create/', MovimentacaoCreateView.as_view(), name='movimentacao_form'),
        path('detail/<int:pk>/', MovimentacaoDetailView.as_view(), name='movimentacao_detail'),
        path('pdf_movimentacao/<int:pk>/', GerarPdfMovimentacaoView.as_view(), name='movimentacao_pdf')
    ])),
  ]

confraria/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from confraria.pessoa.views import Intro
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', Intro.as_view(), name='home'),
    path('pessoa/', include('confraria.pessoa.urls')),
    path('produto/', include('confraria.produto.urls')),
    path('evento/', include('confraria.evento.urls')),
]

confraria/produto/models.py
from django.db import models
from django.db.models import Sum
from django.db.models import Max


class TipoMovimentacaoChoices(models.TextChoices):
    ENTRADA = 'entrada', 'Entrada'
    SAIDA = 'saida', 'Saída'


class Categoria(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return self.name


class Produto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)  # de um para muitos
    nome = models.CharField(max_length=200)
    descricao = models.TextField(blank=True)

    class Meta:
        ordering = ('nome',)
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'

    def __str__(self):
        if self.descricao:
            return f'{self.nome} ({self.descricao[:15]})'
        return self.nome

    @property
    def total_entrada(self):
        return self.movimentacao_set.filter(
            tipo=TipoMovimentacaoChoices.ENTRADA
        ).aggregate(total=Sum('movimentacaoproduto__quantidade')).get('total') or 0

    @property
    def total_saida(self):
        return self.movimentacao_set.filter(
            tipo=TipoMovimentacaoChoices.SAIDA
        ).aggregate(total=Sum('movimentacaoproduto__quantidade')).get('total') or 0

    @property
    def estoque(self):
        return self.total_entrada - self.total_saida

    @property
    def disponibilidade(self):
        if self.estoque < 1:
            return False
        return True


class Movimentacao(models.Model):
    tipo = models.CharField('Tipo', max_length=128, choices=TipoMovimentacaoChoices.choices)
    data = models.DateTimeField()
    observacao = models.TextField(blank=True, null=True, verbose_name='Observações')
    numero_oficio = models.IntegerField(blank=True, null=True, unique=True)
    produtos = models.ManyToManyField(
        Produto,
        through='MovimentacaoProduto',
        through_fields=('movimentacao', 'produto'),
    )

    class Meta:
        verbose_name = 'Movimentação'
        verbose_name_plural = 'Movimentações'

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.numero_oficio = Movimentacao.objects.aggregate(Max('numero_oficio'))['numero_oficio__max'] + 1
        super(Movimentacao, self).save(*args, **kwargs)

    @property
    def quantidade(self):
        return self.produtos.aggregate(total=Sum('movimentacaoproduto__quantidade')).get('total') or 0

    @property
    def pessoas_envolvidas(self):
        return self.movimentacaoproduto_set.order_by(
            'pessoa__nome'
        ).distinct().values_list('pessoa__nome', flat=True)

    @property
    def produtos_envolvidos(self):
        return self.movimentacaoproduto_set.order_by(
            'produto__nome'
        ).distinct().values_list('produto__nome', flat=True)

    def __str__(self):
        return 'OFÍCIO {} | Tipo: {} | Data: {}'.format(
            self.numero_oficio,
            self.tipo,
            self.data
        )


class MovimentacaoProduto(models.Model):
    movimentacao = models.ForeignKey(Movimentacao, on_delete=models.PROTECT)
    produto = models.ForeignKey(Produto, on_delete=models.PROTECT)
    pessoa = models.ForeignKey('pessoa.Pessoa', on_delete=models.PROTECT)
    quantidade = models.PositiveSmallIntegerField()

    def __str__(self):
        return 'OFÍCIO {} | {} para {} | QTD: {}'.format(
            self.movimentacao.numero_oficio,
            self.produto,
            self.pessoa,
            self.quantidade
        )

confraria/produto/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import inlineformset_factory
from django.forms.models import BaseInlineFormSet

from .models import MovimentacaoProduto, Produto, Movimentacao, TipoMovimentacaoChoices, Categoria


class MovimentacaoProdutoForm(forms.ModelForm):
    class Meta:
        model = MovimentacaoProduto
        fields = [
            'produto',
            'quantidade',
            'pessoa',
        ]

    def __init__(self, *args, **kwargs):
        self.tipo = kwargs.pop('tipo')
        super().__init__(*args, **kwargs)
        self.fields['pessoa'].queryset = self.fields['pessoa'].queryset.order_by('nome')

    def clean_quantidade(self):
        value = self.cleaned_data['quantidade']
        if self.tipo == TipoMovimentacaoChoices.SAIDA and value > self.cleaned_data['produto'].estoque:
            self.add_error('quantidade', 'Não há estoque suficiente para a operação!')
        return value


class BaseMovimentacaoFormSet(BaseInlineFormSet):
    def clean(self):
        qtd_total = {}
        tipo = self.forms[0].tipo
        for form in self.forms:
            produto = form.cleaned_data.get('produto')
            quantidade = form.cleaned_data.get('quantidade')
            pessoa = form.cleaned_data.get('pessoa') or self.forms[0].cleaned_data.get('pessoa')
            if not pessoa:
                form.add_error('pessoa', 'Pessoa é obrigatória')
            if produto and quantidade:
                try:
                    qtd_total[produto.pk] += quantidade
                except KeyError:
                    qtd_total[produto.pk] = quantidade
            else:
                if not produto:
                    form.add_error('produto', 'Produto é obrigatório')
                if not quantidade:
                    form.add_error('quantidade', 'Quantidade é obrigatória')
        for produto_pk, quantidade in qtd_total.items():
            produto = Produto.objects.get(pk=produto_pk)
            if tipo == TipoMovimentacaoChoices.SAIDA and produto.estoque < quantidade:
                raise ValidationError('Sem estoque para operação')


MovimentacaoFormSet = inlineformset_factory(
    Movimentacao,
    MovimentacaoProduto,
    form=MovimentacaoProdutoForm,
    formset=BaseMovimentacaoFormSet,
    fk_name='movimentacao',
    fields=('produto', 'quantidade', 'pessoa'),
    extra=1
)


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = [
            'nome',
            'descricao',
            'categoria',
        ]
    # continuar


class MovimentacaoForm(forms.ModelForm):
    class Meta:
        model = Movimentacao
        fields = [
            'tipo',
            'data',
            'observacao',
        ]


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['name']

confraria/produto/views.py
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DetailView, View
from django.urls import reverse_lazy

from confraria.mixins import FormsetMixin
from .forms import ProdutoForm, MovimentacaoForm, CategoriaForm, MovimentacaoFormSet
from .models import Produto, Movimentacao, Categoria

# pdf

from django.template.loader import render_to_string
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from weasyprint import HTML


class ProdutoListView(LoginRequiredMixin, ListView):
    model = Produto
    paginate_by = 15

    def get_queryset(self):
        nome_produto = self.request.GET.get('nome')
        produto_disponivel = self.request.GET.get('disponibilidade')
        produtos = super(ProdutoListView, self).get_queryset()
        q = Q()
        objects_id = (obj.id for obj in produtos if obj.disponibilidade is True)

        if nome_produto:
            q = q & Q(nome__icontains=nome_produto)

        if produto_disponivel:
            q = q & Q(id__in=objects_id)

        produtos = produtos.filter(q).order_by("nome")

        return produtos


class ProdutoCreateView(LoginRequiredMixin, CreateView):
    model = Produto
    form_class = ProdutoForm

    def get_success_url(self):
        return reverse_lazy('produto_list')


class ProdutoUpdateView(LoginRequiredMixin, UpdateView):
    model = Produto
    form_class = ProdutoForm

    def get_success_url(self):
        return reverse_lazy('produto_list')


class MovimentacaoListView(LoginRequiredMixin, ListView):
    model = Movimentacao
    paginate_by = 15
    ordering = ['-data']


class MovimentacaoCreateView(LoginRequiredMixin, FormsetMixin, CreateView):
    model = Movimentacao
    form_class = MovimentacaoForm
    formset_class = MovimentacaoFormSet

    def get_formset_kwargs(self):
        kwargs = super().get_formset_kwargs()
        form = self.get_form()
        kwargs['form_kwargs'] = {
            'tipo': form['tipo'].value()
        }
        return kwargs

    def get_success_url(self):
        return reverse_lazy('movimentacao_list')


class MovimentacaoDetailView(LoginRequiredMixin, DetailView):
    model = Movimentacao


class CategoriaCreateView(LoginRequiredMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm

    def get_success_url(self):
        return reverse_lazy('categoria_list')


class CategoriaListView(LoginRequiredMixin, ListView):
    model = Categoria


class GerarPdfMovimentacaoView(View):
    def generate_pdf(self, obj):
        html_string = render_to_string('reports/pdf_template_movimentacao.html', {'obj': obj})
        link = obj.numero_oficio
        html = HTML(string=html_string, base_url=self.request.build_absolute_uri())
        html.write_pdf(target=f'/tmp/{link}.pdf')

        fs = FileSystemStorage('/tmp')
        with fs.open(f'{link}.pdf') as pdf:
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Transfer-Encoding'] = 'binary'
            response['Content-Disposition'] = 'inline; filename="{}.pdf"'.format(link)

            return response

    def get(self, request, *args, **kwargs):
        obj = Movimentacao.objects.get(pk=kwargs['pk'])
        response = self.generate_pdf(obj)
        return response

confraria/produto/templates/produto/categoria_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
<h1>Adicionar categoria</h1>
{% endblock title %}

{% block content %}
<form method="POST" class="row col-12">
    {% csrf_token %}
    <div class="col-12 row">
        <div class="col-lg-5">
            <label class="h5 text-primary" for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {% render_field form.name class="form-control" placeholder="Nome da categoria" %}
            <div class="invalid-feedback">
                {{ form.name.errors }}
            </div>
        </div>
    </div>
        
    <button type="submit" class="btn btn-success">Salvar</button>
</form>

{% endblock content %}

confraria/produto/templates/produto/categoria_list.html
{% extends 'base.html' %}

{% block title %}
<h1>Categorias</h1>
{% endblock title %}


{% block actions %}
<a href="{% url 'categoria_form' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-plus"></i>
    </span>
    <span class="text">Nova categoria</span>
</a>
{% endblock actions %}


{% block content %}
<div class="container-fluid card mb-4">
    <div class="card-body">
        <div>
            <table class="table table-bordered" id="dataTable">
                <thead>
                    <tr>
                        <th>Nome</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for categoria in object_list %}
                        <tr>
                            <td>{{ categoria.name }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {% include 'pagination.html' %}
    </div>
</div>


{% endblock content %}

confraria/produto/templates/produto/movimentacao_detail.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
<h1>Detalhe da Movimentação</h1>
{% endblock title %}


{% block actions %}
<a href="{% url 'movimentacao_pdf' pk=object.id %}" class="d-sm-inline-block btn btn-sm btn-primary shadow-sm mr-3">
    <i class="fas fa-download fa-sm text-white-50"></i> Gerar PDF
</a>
<a href="{% url 'movimentacao_list' %}" class="btn btn-outline-success">Voltar</a>
{% endblock actions %}


{% block content %}
<div class="col-12">
    <table class="table table-user-information">
        <tbody>
        <tr>
            <th class="text-left">Ofício Nº</th>
            <td>{{ object.numero_oficio }}</td>
        </tr>
        <tr>
            <th class="text-left">Tipo</th>
            <td>{{ object.get_tipo_display }}</td>
        </tr>
        <tr>
            <th class="text-left">Data</th>
            <td>{{ object.data }}</td>
        </tr>
        <tr>
            <th class="text-left">Total</th>
            <td>{{ object.quantidade }}</td>
        </tr>
        </tbody>
    </table>

    <h2>Movimentações</h2>

    <table class="table">
        <thead>
            <th>Produto</th>
            <th>Pessoa</th>
            <th>Quantidade</th>
        </thead>
        <tbody>
            {% for movimentacao in object.movimentacaoproduto_set.all %}
                <tr>
                    <td>{{ movimentacao.produto }}</td>
                    <td>{{ movimentacao.pessoa }}</td>
                    <td>{{ movimentacao.quantidade }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% if object.observacao %}
    <div class="card">
        <h5 class="card-header">Observações</h5>
        <div class="card-body">
          <p class="card-text justify-content-center">{{ object.observacao }} </p>
        </div>
    </div>
{% endif %}
</div>

{% endblock content %}

confraria/produto/templates/produto/movimentacao_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
<h1>Nova Movimentação</h1>
{% endblock title %}

{% block content %}
{% if formset.non_form_errors %}
<div class="alert alert-warning col-12" role="alert">
    <p>{{ formset.non_form_errors }}</p>
</div>
{% endif %}
<form method="POST" class="row col-12">
    {% csrf_token %}
    <div class="col-12 row">
        <div class="col-lg-4">
            <label class="h5 text-primary" for="{{ form.tipo.id_for_label }}">{{ form.tipo.label }}</label>
            {% render_field form.tipo type="date" class="form-control" %}
            <div class="invalid-feedback">
                {{ form.tipo.errors }}
            </div>
        </div>
        <div class="col-lg-4">
            <label class="h5 text-primary" for="{{ form.data.id_for_label }}">{{ form.data.label }}</label>
            {% render_field form.data type="datetime-local" class="form-control" %}
            <div class="invalid-feedback">
                {{ form.data.errors }}
            </div>
        </div>
    </div>
        
    <div class="col-12">
        {{ formset.management_form }}
        <div class="row">
            <h5 class="text-primary col-4 ml-2">Pessoa</h5>
            <h5 class="text-primary col-4 ml-2">Produto</h5>
            <h5 class="text-primary col-2 ml-2">Quantidade</h5>
        </div>
        <div id="movimentacao_list">
            {% for form in formset %}
                <div id="{{ form.prefix }}-item" class="movimentacao_item row align-items-center" >
                    {{ form.id }}
                    <div class="col-4 ml-2">
                        {% render_field form.pessoa class="form-control" %}
                        <div class="invalid-feedback">
                            {{ form.pessoa.errors }}
                        </div>
                    </div>
                    <div class="col-4 ml-2">
                        {% render_field form.produto class="form-control" %}
                        <div class="invalid-feedback">
                            {{ form.produto.errors }}
                        </div>
                    </div>
                    <div class="col-2 ml-2">
                        {% render_field form.quantidade class="form-control" %}
                        <div class="invalid-feedback">
                            {{ form.quantidade.errors }}
                        </div>
                    </div>
                    <div>
                        <button
                            id="{{ form.prefix }}-button"
                            type="button"
                            class="btn btn-danger btn-sm"
                            onclick="removeLine(this)"
                        >X</button>
                    </div>
                </div>
            {% endfor %}
        </div>
        <button type="button" id="add_item_id" class="btn btn-primary">Registro <i class="fas fa-plus"></i></button>
    </div>

    <div class="col-lg-10">
        <label class="h5 text-primary text-right" for="{{ form.observacao.id_for_label }}">{{ form.observacao.label }}</label>
        {% render_field form.observacao class="form-control" rows="3" placeholder="Observações importantes" %}
        <div class="invalid-feedback">
            {{ form.observacao.errors }}
        </div>
    </div>

    <div class="col-12 my-2 d-flex justify-content-center">
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>
</form>

{% endblock content %}

{% block extra_js %}

<script type="text/javascript">

    function removeLine (element) {
        div_id = element.id.replace('-button', '-item')
        lineToRemove = document.getElementById(div_id)
        lineToRemove.remove()
        let totalForms = document.querySelector("#id_movimentacaoproduto_set-TOTAL_FORMS")
        let totalFormNum = parseInt(totalForms.value)
        totalFormNum--
        totalForms.setAttribute('value', `${totalFormNum}`)
    }

    $(document).ready(function() {
        $("#add_item_id").click(function(e) {
            e.preventDefault()
            let itens = document.querySelectorAll('.movimentacao_item')
            let formNum = itens.length
            let totalForms = document.querySelector("#id_movimentacaoproduto_set-TOTAL_FORMS")
            let totalFormNum = parseInt(totalForms.value)
            let container = document.querySelector("#movimentacao_list")

            let newForm = itens[formNum-1].cloneNode(true)
            let formRegex = RegExp(`movimentacaoproduto_set-(\\d+){1}-`,'g')

            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `movimentacaoproduto_set-${formNum}-`)
            newForm.id = newForm.id.replace(formRegex, `movimentacaoproduto_set-${formNum}-`)
            container.insertBefore(newForm, null)
            totalFormNum++
            totalForms.setAttribute('value', `${totalFormNum}`)
        });
    });

</script>

{% endblock extra_js %}

confraria/produto/templates/produto/movimentacao_list.html
{% extends 'base.html' %}

{% block title %}
<h1>Movimentações</h1>
{% endblock title %}

{% block actions %}
<a href="{% url 'movimentacao_form' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-plus"></i>
    </span>
    <span class="text">Nova movimentação</span>
</a>
{% endblock actions %}


{% block content %}
<div class="container-fluid card mb-4">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>Ofício Nº</th>
                        <th>Tipo</th>
                        <th>Quantidade</th>
                        <th>Produtos Envolvidos</th>
                        <th>Pessoas Envolvidas</th>
                        <th>Data</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for movimentacao in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'movimentacao_detail' pk=movimentacao.pk %}">{{ movimentacao.numero_oficio}}</a>
                            </td>

                            <td>{{ movimentacao.tipo|default_if_none:'--' }}</td>
                            <td>{{ movimentacao.quantidade|default_if_none:'--'}}</td>
                            <td>
                                {% if movimentacao.produtos_envolvidos|length > 2 %}
                                    {{ movimentacao.produtos_envolvidos|slice:":2"|join:', ' }}
                                {% else %}
                                    {{ movimentacao.produtos_envolvidos|join:', ' }}
                                {% endif %}
                            </td>
                            <!-- <td>{{ movimentacao.produtos.first|default_if_none:'--'}}</td> -->

                            <td>
                                {% if movimentacao.pessoas_envolvidas|length > 2 %}
                                    {{ movimentacao.pessoas_envolvidas|slice:":2"|join:', ' }} (...)
                                {% else %}
                                    {{ movimentacao.pessoas_envolvidas|join:', ' }}
                                {% endif %}
                            </td>
                            <td>{{ movimentacao.data|default_if_none:'--' }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {% include 'pagination.html' %}
    </div>
</div>

{% endblock content %}

confraria/produto/templates/produto/produto_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block title %}
<h1>Cadastrar Produto</h1>
{% endblock title %}

{% block content %}
<form method="POST" class="row col-12">
    {% csrf_token %}
    <div class="col-12 row">
        <div class="col-lg-6">
            <label class="h5 text-primary" for="{{ form.nome.id_for_label }}">{{ form.nome.label }}</label>
            {% render_field form.nome class="form-control" placeholder="Nome do produto" %}
            <div class="invalid-feedback">
                {{ form.nome.errors }}
            </div>
        </div>
        <div class="col-lg-4">
            <label class="h5 text-primary" for="{{ form.categoria.id_for_label }}">{{ form.categoria.label }}</label>
            <a href="javascript:newPopup()"><i class="fas fa-plus"></i></a>
            {% render_field form.categoria type="date" class="form-control" %}
            <div class="invalid-feedback">
                {{ form.categoria.errors }}
            </div>
        </div>
        <div class="col-lg-12">
            <label class="h5 text-primary" for="{{ form.descricao.id_for_label }}">{{ form.descricao.label }}</label>
            {% render_field form.descricao class="form-control" placeholder="Descricao do produto" %}
            <div class="invalid-feedback">
                {{ form.descricao.errors }}
            </div>
        </div>
    </div>
        
    <div class="col-lg-6">
        
    </div>
    <div class="col-lg-6">

    </div>
    <button type="submit" class="btn btn-success">Salvar</button>
</form>

{% endblock content %}

confraria/produto/templates/produto/produto_list.html
{% extends 'base.html' %}

{% block title %}
<h1>Produtos</h1>
{% endblock title %}


{% block actions %}
<a href="{% url 'produto_form' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
        <i class="fas fa-plus"></i>
    </span>
    <span class="text">Novo Produto</span>
</a>
{% endblock actions %}


{% block content %}
<div class="container-fluid card mb-4">
    <hr>
    <div class="card-body">
        <div class="row-12 col-12">
            <form method="get" class="d-flex">
                <div class="row-4 col-4">
                <input class="form-control me-2" id="search" type="text" name="nome" placeholder="Procure pelo Nome do Produto" aria-label="Search" value="{{request.GET.nome}}">
                </div>
                <div class="row-4 col-3">
                <input type="checkbox" id="search-checkbox" name="disponibilidade">
                <label for="search-checkbox">Produto Disponível</label>
                </div>
                <div class="row">
                <button class="btn btn-outline-success" type="submit">Procurar</button>
                </div>
            </form>
        <div>
    <hr>
        <div class="table-responsive">
            <table class="table table-bordered" width="100%" id="dataTable" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Descrição</th>
                        <th>Categoria</th>
                        <th>Disponibilidade</th>
                        <th>Quantidade</th>
                    </tr>
                </thead>
                
                <tbody>
                    {% for produto in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'produto_form' pk=produto.pk %}">{{ produto.nome }}</a>
                            </td>
                            <td>{{ produto.descricao|default_if_none:'--' }}</td>
                            <td>{{ produto.categoria|default_if_none:'--' }}</td>
                            <td>{% if produto.disponibilidade %}
                                    <i class="fa fa-check-circle ok"></i>
                                {% else %}
                                    <i class="fa fa-minus-circle no"></i>
                                {% endif %}
                            </td>
                            <td>{{ produto.estoque|default_if_none:'--'  }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer d-flex justify-content-center">
        {% include 'pagination.html' %}
    </div>
</div>

{% endblock content %}